[build]
  publish = "."
  command = "npm install"

[[redirects]]
  from = "/"
  to = "/room.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/models/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.gltf"
    [headers.values]
    Content-Type = "model/gltf+json"

[[headers]]
  for = "/*.glb"
    [headers.values]
    Content-Type = "model/gltf-binary"

[[headers]]
  for = "/images/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
    [headers.values]
    Cache-Control = "public, max-age=31536000"
